### ISSUE TITLE
[Setup] Create a Speakers landing page for marketing

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/speakers#28]
**Why**: The speakers catalogue will be announced around COP so the website needs to look presentable and user friendly by then
**Scope of work**
- [ ] Create a figma design with speakers landing page
- - Logo (https://github.com/Green-Software-Foundation/speakers/issues/27)
- - Title: Green Software Speakers
- - Copy: 

---

_No major IT conference should take place without at least one green software speaker._

Finding those speakers can be hard which is why the Green Software Foundation has created this comprehensive catalogue of speakers in the area of green software. It also facilitates the search and booking of world-class speakers in the green software space.

Contacting individual or multiple speakers is made easy and secure through the platform. You will be able to search by areas of expertise, by certifications, geography, languages, and more to find the right speaker for your event.

[Call To Actions]

I'm an event organizer:
- Browse our catalog (goto /speakers)
- Submit a Call for Papers (goto https://grnsft.org/speakers/find )

I'm a speaker:
- I want to be added as a speaker (goto https://grnsft.org/speakers/apply)

---

- [x] Post figma for reviews by @jawache @holanita 
- [x] Implement design as a new index.mdx
- [ ] Move current index.mdx to team.mdx

**Comment by zanete** [comment]
need to organise some landing page copy (from Book of News)

**Comment by jawache** [comment]
The existing landing page is more like a project team page. Let's rename index.mdx to team.mdx

The new landing page (index.mdx) should be a little but more like a marketing page. Let's use the content from the Book of News as inspiration:

---
[LOGO] 

**Green Software Speakers**

_No major IT conference should take place without at least one green software speaker._ 

Finding those speakers can be hard which is why the Green Software Foundation has created this comprehensive catalogue of speakers in the area of green software. It also facilitates the search and booking of world-class speakers in the green software space. 

Contacting individual or multiple speakers is made easy and secure through the platform. You will be able to search by areas of expertise, by certifications, geography, languages, and more to find the right speaker for your event. 

[Call To Actions]

I'm looking for a speaker
I am a speaker

**Comment by zanete** [comment]
@jawache Do I understand correctly, 
(1) the "Submit a Call For Papers" is going to the same form as "Looking for speakers" on the top of the speakers website as per #26? 
(2) if so, should the Call to action text be the same across the site or can be different?

**Comment by holanita** [comment]
@zanete @osamajandali sounds like the major task is completed here and it turned out great! I tried to find in the source files the team.mdx that Asim mentioned above, but I couldn't. do we still need that?

**Comment by zanete** [comment]
@holanita the team.mdx file task is no longer needed as Osama changed the technical solution completely. 
the contact us button opens an email app and expects you to write an email. is there something else that you were hoping it does? if so, i would suggest raising another task so it can be prioritised / tracked separately.

**Comment by holanita** [comment]
@zanete what I mentioned above is that the contact us button doesn't work at all. it doesn't do anything at all. can we fix this now as this seems to be part of the task to create the landing page? 

I don't know who added that section and what the idea was behind this. if this needs to be linked to a google form, please use this one that I just created: https://forms.gle/jL57mfDzTofHaRuC7

**Comment by zanete** [comment]
@holanita what device/browser are you using? For me it opens a mailto: link but yes, that form can be a great substitute. I will add a separate issue for this.
