### ISSUE TITLE
Not able to add new profiles – Node js issue

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/speakers#39]
@osamajandali on Friday I tried to add some new speakers and all my attempts failed. First I thought it was just my mistake, as I created some wrong files. But I wasn't even able to delete the wrong ones, which was suspicious. Looking at the details of the failed [actions](https://github.com/Green-Software-Foundation/speakers/actions), there might be a node js issue here »

_Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout_

**Comment by holanita** [comment]
I tried again this morning because 9 speakers are waiting to be added since last Thursday and I wanted to make sure it's not me who is making some mistake here. [My new attempt](https://github.com/Green-Software-Foundation/speakers/actions/runs/3469214903) failed again. Let me know when you have updates on this. Thanks.

**Comment by osamajandali** [comment]
It was a very silly thing that caused all of this trouble..you were using `–` instead of `-` .. it is a very subtle typo, but for the computer program, they are different 😄 
here is the fix:
https://github.com/Green-Software-Foundation/speakers/commit/e46c34a30ebdfdaa721c93f1a6231e1f9dde25ea#diff-7b984ae541b24268d20639bc7c144f14c53953249bb8d1f93d6b3dd18cadf61dL10

**Comment by holanita** [comment]
ok thanks
